apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apigee-20-datastore-np-test-ntt
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '20'
spec:
  project: default
  source:
    repoURL: https://github.com/MathewLove17/apigeehybrid.git
    targetRevision: main
    path: charts/apigee-datastore
    helm:
      valueFiles:
      - ../../overrides/overrides_np-test-ntt_v1.15.1.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: apigee
  syncPolicy:
    syncOptions:
    - CreateNamespace=false
    - ServerSideApply=true
    automated:
      prune: false
      selfHeal: true
