apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apigee-20-datastore
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: default
  source:
    repoURL: https://github.com/MathewLove17/apigeehybrid.git
    targetRevision: main
    path: charts/apigee-datastore
    helm:
      valueFiles:
        - ../../overrides/overrides_V15_test.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: apigee
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=false